version: '3.5'
services:
  solr:
    image: solr:6.6.5
    ports:
      - 8983:8983
    volumes:
      - solr_data:/opt/solr/server/solr:rw

  postgres:
    image: postgres:14.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: gobotany
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  goorchids:
    build: .
    image: ghcr.io/jazkarta/goorchids:latest
    depends_on:
      - solr
      - postgres
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./goorchids:/opt/goorchids/goorchids
      - ./external:/opt/goorchids/external
    environment:
      GOBOTANY_DJANGO_SECRET_KEY: "secret"

volumes:
  postgres_data:
  solr_data:
