version: '3.5'
services:
  solr:
    image: solr:6.6.5
    networks:
      - goorchirds

  postgres:
    image: postgres:14.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: gobotany
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks:
      - goorchirds

  goorchids:
    build: .
    image: goorchids:latest
    depends_on:
      - solr
      - postgres
    ports:
      - '8000:8000'
      - '8001:8001'
    volumes:
      - ./goorchids:/opt/goorchids/goorchids
      - ./external:/opt/goorchids/external
    environment:
      GOBOTANY_DJANGO_SECRET_KEY: "secret"
    networks:
      - goorchirds

volumes:
  postgres_data:

networks:
  goorchirds:
