version: '3.5'
services:
  solr:
    image: solr:6.6.5
    ports:
      - 8983:8983
    volumes:
      - solr_data:/opt/solr/server/solr:rw
    networks:
      - goorchirds

  postgres:
    image: postgres:14.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: gobotany
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks:
      - goorchirds

  redis:
    image: redis:7.0.11-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - goorchirds

  goorchids:
    build: .
    image: ghcr.io/jazkarta/goorchids:latest
    depends_on:
      - solr
      - postgres
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./goorchids:/opt/goorchids/goorchids
      - ./external:/opt/goorchids/external
    environment:
      GOBOTANY_DJANGO_SECRET_KEY: "secret"
      REDIS_URL: redis://redis:6379
    networks:
      - goorchirds

  worker:
    build: .
    image: ghcr.io/jazkarta/goorchids:latest
    command: python worker.py
    depends_on:
      - redis
    volumes:
      - ./goorchids:/opt/goorchids/goorchids
      - ./external:/opt/goorchids/external
    environment:
      GOBOTANY_DJANGO_SECRET_KEY: "secret"
      REDIS_URL: redis://redis:6379
    networks:
      - goorchirds

volumes:
  postgres_data:
  solr_data:
  redis_data:

networks:
  goorchirds:
