- name: Include users
  ansible.builtin.include_vars: ../vars/users.yml

- name: "Create users"
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: present
    shell: /bin/bash
    groups:
      - docker
      - sudo
  with_items: "{{ remote_users }}"
  become: true

- name: Ensure /home/<user>/.ssh exists
  ansible.builtin.file:
    dest: /home/{{ item.username }}/.ssh
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0700"
  with_items: "{{ remote_users }}"
  become: true

- name: Place ssh keys
  ansible.builtin.copy:
    dest: /home/{{ item.username }}/.ssh/authorized_keys
    content: "{{ item.key }}"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0700"
  with_items: "{{ remote_users }}"
  become: true

- name: Ensure user can sudo without password
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/{{ item.username }}
    state: present
    create: true
    regexp: '^{{ item.username }} ALL='
    line: '{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true
  with_items: "{{ remote_users }}"
