- name: Deploy
  hosts: staging
  vars:
    goorchids_user: goorchids
  tasks:
    - name: Install docker
      ansible.builtin.include_tasks: tasks/docker.yml
    - name: Create users
      ansible.builtin.include_tasks: tasks/users.yml

    - name: Create user {{ goorchids_user }}
      ansible.builtin.user:
        name: "{{ goorchids_user }}"
        state: present
        group: docker
      tags:
        - users

    - name: Clone git repository
      ansible.builtin.git:
        repo: https://github.com/Jazkarta/goorchids-app.git
        dest: /home/{{ goorchids_user }}/goorchids-app
        version: "{{ lookup('env', 'GOORCHIDS_VERSION') or 'master' }}"
      become_user: "{{ goorchids_user }}"
      become: true

    - name: Start dev server
      become: true
      become_user: "{{ goorchids_user }}"
      ansible.builtin.command: docker compose up -d
      changed_when: false
      args:
        chdir: /home/{{ goorchids_user }}/goorchids-app
      tags:
        - users
