# Generated by Django 3.1.13 on 2022-05-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goorchids_core', '0003_auto_20160113_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='success',
            field=models.BooleanField(null=True),
        )
    ]
